refresh_rate = 30

[appenders.console]
  kind = "console"

[appenders.console.encoder]
  pattern = "{d(%Y-%m-%d %H:%M:%S)} {h({l})} - {m}{n}"

[[appenders.console.filter]]
  kind = "threshold"
  level = "info"

[appenders.requests]
  kind = "file"
  path = "logs/requests.log"

[root]
  level = "info"
  appenders = ["console"]
  additive = true

[loggers."commitsparkles::handlers"]
  level = "debug"
  appenders = ["requests"]
