refresh_rate = 30

[appenders.stdout]
  kind = "console"

[appenders.requests]
  kind = "file"
  path = "logs/requests.log"

[root]
  level = "info"
  appenders = ["stdout"]
  additive = true

[loggers."commitsparkles::handlers"]
  level = "debug"
  appenders = ["requests"]
